### PR TITLE
New Mindmap section

### PR DESCRIPTION
**Pull request by IT-Berater**
Add a new Mindmap section

### CODE REVIEW

**Comment by dsopas** [comment]
@IT-Berater It seems some people check the changes before merging the PR :) What was the objective by updating the files you wanted? I'm curious on your reply.

**Comment by IT-Berater** [comment]
Sorry, only references.md updated.

**Comment by dsopas** [comment]
@IT-Berater No problem but you didn't answer my question. What was the objective of changing the other files?

**Comment by IT-Berater** [comment]
I add a new Mindmap sction:
## Mindmaps
- [TOP 10 Critical Cyber Safety Lessons To Teach Your Kids](http://kleinhirn.eu/2019/09/03/top-10-critical-cyber-safety-lessons-to-teach-your-kids/)
- [IDOR Techniques Mindmap](https://www.xmind.net/m/CSKSWZ/)

**Comment by IT-Berater** [comment]
I can not remove the wrong commit in the CR.

**Comment by IT-Berater** [comment]
Wrong test with pages on my Repo.

**Pull request closed without merging**
